[build]
  base = "packages/chapters"
  command = "yarn build"
  functions = "lambda"
  ignore = "git diff --quiet HEAD^ HEAD packages/chapters"
  publish = "public"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
